<!DOCTYPE html>

<html>
<head>
  <title>Interrupt</title>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, target-densitydpi=160dpi, initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  <link rel="stylesheet" media="all" href="docco.css" />
</head>
<body>
  <div id="container">
    <div id="background"></div>

      <ul id="jump_to">
        <li>
          <a class="large" href="javascript:void(0);">Jump To &hellip;</a>
          <a class="small" href="javascript:void(0);">+</a>
          <div id="jump_wrapper">
          <div id="jump_page_wrapper">
            <div id="jump_page">


                <a class="source" href="interrupt.js.html">
                  interrupt.js
                </a>


                <a class="source" href="location.js.html">
                  location.js
                </a>


                <a class="source" href="parse.js.html">
                  parse.js
                </a>


                <a class="source" href="readme.js.html">
                  readme.js
                </a>

            </div>
          </div>
        </li>
      </ul>

    <ul class="sections">



        <li id="section-1">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-1">&#182;</a>
              </div>
              <h1 id="interrupt">Interrupt</h1>

            </div>

        </li>


        <li id="section-2">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-2">&#182;</a>
              </div>
              <p>Exceptions are useful. I like the concept. I’ve always been able to program
try/catch in Node.js regardless of whether a function is synchronous or
asynchronous because I’ve always programmed with <code>cadence</code> which has a nice
implementation of asynchronous <code>try</code>/<code>catch</code>.</p>

            </div>

        </li>


        <li id="section-3">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-3">&#182;</a>
              </div>
              <p>Interrupt as an <code>Error</code> generator allows me to gather up errors from many
different waiting asynchronous calls and report them in a bouquet of failures
on the command line and in my server logs. Interrupt supports nested
exceptions, context for exceptions and complete error reports on fatal error
exit.</p>

            </div>

        </li>


        <li id="section-4">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-4">&#182;</a>
              </div>
              <p>It does this using the <code>stack</code> property which is specific to Node.js and
Interrupt is therefore Node.js specific. If there is interest in using
Interrupt outside of Node.js, let me know where and I’ll have a look at what
it would take to adapt it to a new JavaScript environment.</p>

            </div>

        </li>


        <li id="section-5">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-5">&#182;</a>
              </div>
              <p>Interrupt generates elaborate stack trace messages that include formatted
messages, contextual data and the stack traces of nested exceptions. You can
view examples of these stack traces by running this program.</p>
<pre><code>node readme</code></pre>
            </div>

        </li>


        <li id="section-6">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-6">&#182;</a>
              </div>
              <p>In JavaScript, Error defined as some arbitrary object with an <code>Error</code> type
and a <code>message</code> property. It is, in itself, not very useful. Node.js makes it
more informative by adding a stack trace. With the stack trace you get an
idea of where in your code the exception occurred.</p>

            </div>

        </li>


        <li id="section-7">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-7">&#182;</a>
              </div>
              <p>Not always though, because sometimes the errors occur in the Node.js event
loop while handling sockets and files.</p>

            </div>

        </li>


        <li id="section-8">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-8">&#182;</a>
              </div>
              <p>To use Interrupt install it from NPM using the following.</p>
<pre><code>npm install interrupt</code></pre><p>Then you can begin to use it in your code as follows.</p>

            </div>

        </li>


        <li id="section-9">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-9">&#182;</a>
              </div>

            </div>

            <div class="content"><div class='highlight'><pre><span class="hljs-keyword">const</span> Interrupt = <span class="hljs-built_in">require</span>(<span class="hljs-string">'.'</span>)</pre></div></div>

        </li>


        <li id="section-10">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-10">&#182;</a>
              </div>

            </div>

        </li>


        <li id="section-11">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-11">&#182;</a>
              </div>
              <p>We’ll use <code>assert</code> to illustrate some of our points in this document.</p>

            </div>

        </li>


        <li id="section-12">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-12">&#182;</a>
              </div>

            </div>

            <div class="content"><div class='highlight'><pre><span class="hljs-keyword">const</span> assert = <span class="hljs-built_in">require</span>(<span class="hljs-string">'assert'</span>)</pre></div></div>

        </li>


        <li id="section-13">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-13">&#182;</a>
              </div>

            </div>

        </li>


        <li id="section-14">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-14">&#182;</a>
              </div>
              <p>Now that you have <code>Interrupt</code> in your code you can define an Error class to
use in your application with <code>Interrupt.create()</code>.</p>
<p><code>Interrupt.create(className, [ superclass ], [ prefix ], [ messages ])</code>
&mdash; creates a new error class derrived from Interrupt.</p>
<ul>
<li><code>className</code> &mdash; The class name of the new error class.</li>
<li><code>superclass</code> &mdash; Optional superclass from which the new class is
derrived. The given superclass <strong>must</strong> be a descendent of <code>Interrupt</code>. If
not provided the superclass will be derived from <code>Interrupt</code> directly.</li>
<li><code>messages</code> &mdash; Optional map of error codes for <code>util.format()</code> error
messages.</li>
</ul>
<p><strong>TODO</strong> Maybe use <code>sprintf</code> and then we can use named arguments from the
context.</p>

            </div>

        </li>


        <li id="section-15">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-15">&#182;</a>
              </div>

            </div>

            <div class="content"><div class='highlight'><pre><span class="hljs-keyword">const</span> FooError = Interrupt.create(<span class="hljs-string">'FooError'</span>, {
    <span class="hljs-string">'FOO_NOT_READY'</span>: <span class="hljs-string">'not ready to process your request'</span>,
    <span class="hljs-string">'FOO_INVALID_ARGMUMENT'</span>: <span class="hljs-string">'invalid argument value'</span>,
    <span class="hljs-string">'FOO_NOT_FOUND'</span>: <span class="hljs-string">'unable to find a value for key; key %s'</span>
})</pre></div></div>

        </li>


        <li id="section-16">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-16">&#182;</a>
              </div>

            </div>

        </li>


        <li id="section-17">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-17">&#182;</a>
              </div>
              <p>We’ve created created a <code>FooError</code> which is a decendent of <code>Interrupt</code>.</p>

            </div>

        </li>


        <li id="section-18">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-18">&#182;</a>
              </div>

            </div>

            <div class="content"><div class='highlight'><pre>assert(FooError.prototype <span class="hljs-keyword">instanceof</span> Interrupt)</pre></div></div>

        </li>


        <li id="section-19">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-19">&#182;</a>
              </div>
              <p>The generated <code>FooError</code> class has a <code>messages</code> property that will list the
messages by error code.</p>

            </div>

        </li>


        <li id="section-20">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-20">&#182;</a>
              </div>

            </div>

            <div class="content"><div class='highlight'><pre><span class="hljs-built_in">console</span>.log(<span class="hljs-string">'--- FooError codes and messages ---\n'</span>)

<span class="hljs-keyword">for</span> (<span class="hljs-keyword">const</span> code <span class="hljs-keyword">in</span> FooError.messages) {
    <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'%s =&gt; %s'</span>, code, FooError.messages[code])
}

{
    <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">parse</span> (<span class="hljs-params">string</span>) </span>{
        <span class="hljs-keyword">try</span> {
            <span class="hljs-keyword">return</span> <span class="hljs-built_in">JSON</span>.parse(string)
        } <span class="hljs-keyword">catch</span> (error) {
            <span class="hljs-keyword">throw</span> <span class="hljs-keyword">new</span> FooError(<span class="hljs-string">'FOO_NOT_READY'</span>, error)
        }
    }
    <span class="hljs-keyword">try</span> {
        parse(<span class="hljs-string">'['</span>)
    } <span class="hljs-keyword">catch</span> (error) {
        <span class="hljs-built_in">console</span>.log(error.stack)
    }
}</pre></div></div>

        </li>


        <li id="section-21">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-21">&#182;</a>
              </div>
              <p>Now we can raise exceptions of type <code>FooError</code>.</p>

            </div>

        </li>


        <li id="section-22">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-22">&#182;</a>
              </div>

            </div>

            <div class="content"><div class='highlight'><pre><span class="hljs-built_in">console</span>.log(<span class="hljs-string">'\n--- Throw a FooError ---\n'</span>)

<span class="hljs-keyword">try</span> {
    <span class="hljs-keyword">throw</span> <span class="hljs-keyword">new</span> FooError(<span class="hljs-string">'FOO_NOT_READY'</span>)
} <span class="hljs-keyword">catch</span> (error) {
    assert(error.code == <span class="hljs-string">'FOO_NOT_READY'</span>)
    <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'Caught error of type %s with code %s. Stack trace follows.\n'</span>, error.name, error.code)

    <span class="hljs-built_in">console</span>.log(error.stack)
}</pre></div></div>

        </li>


        <li id="section-23">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-23">&#182;</a>
              </div>
              <p>There is also a basic assert function you can use, one that tests a single
value for truthiness. We do not provide the full compliment of assertion
helpers from the Node.js <code>assert</code> module, just basic <code>assert</code>. If you want to
compare something just use an operator.</p>

            </div>

        </li>


        <li id="section-24">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-24">&#182;</a>
              </div>

            </div>

            <div class="content"><div class='highlight'><pre><span class="hljs-keyword">try</span> {</pre></div></div>

        </li>


        <li id="section-25">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-25">&#182;</a>
              </div>
              <p>A silly comparison.</p>

            </div>

            <div class="content"><div class='highlight'><pre>    FooError.assert(FooError === <span class="hljs-number">1</span>, <span class="hljs-string">'FOO_INVALID_ARGMUMENT'</span>)
} <span class="hljs-keyword">catch</span> (error) {
    assert(error.code == <span class="hljs-string">'FOO_INVALID_ARGMUMENT'</span>)
    <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'Caught error of type %s with code %s. Stack trace follows.\n'</span>, error.name, error.code)

    <span class="hljs-built_in">console</span>.log(error.stack)
}</pre></div></div>

        </li>


        <li id="section-26">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-26">&#182;</a>
              </div>
              <p>We can add context to our exceptions by calling the contructor with an object
that contains JSON serializable context properties.</p>

            </div>

        </li>


        <li id="section-27">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-27">&#182;</a>
              </div>

            </div>

            <div class="content"><div class='highlight'><pre><span class="hljs-keyword">try</span> {</pre></div></div>

        </li>


        <li id="section-28">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-28">&#182;</a>
              </div>
              <p>Some silly context values.</p>

            </div>

            <div class="content"><div class='highlight'><pre>    <span class="hljs-keyword">throw</span> <span class="hljs-keyword">new</span> FooError(<span class="hljs-string">'FOO_INVALID_ARGMUMENT'</span>, { <span class="hljs-attr">name</span>: <span class="hljs-string">'value'</span>, <span class="hljs-attr">count</span>: <span class="hljs-number">3</span> })
} <span class="hljs-keyword">catch</span> (error) {
    assert(error.code == <span class="hljs-string">'FOO_INVALID_ARGMUMENT'</span>)
    <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'Caught error of type %s with code %s. Stack trace follows.\n'</span>, error.name, error.code)

    <span class="hljs-built_in">console</span>.log(error.stack)
}</pre></div></div>

        </li>


        <li id="section-29">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-29">&#182;</a>
              </div>
              <p>Context values also work with <code>assert</code>.</p>

            </div>

        </li>


        <li id="section-30">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-30">&#182;</a>
              </div>

            </div>

            <div class="content"><div class='highlight'><pre><span class="hljs-keyword">try</span> {</pre></div></div>

        </li>


        <li id="section-31">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-31">&#182;</a>
              </div>
              <p>Silly things combined.</p>

            </div>

            <div class="content"><div class='highlight'><pre>    FooError.asert(FooError == <span class="hljs-number">1</span>, <span class="hljs-string">'FOO_INVALID_ARGMUMENT'</span>, { <span class="hljs-attr">name</span>: <span class="hljs-string">'value'</span>, <span class="hljs-attr">count</span>: <span class="hljs-number">3</span> })
} <span class="hljs-keyword">catch</span> (error) {
    assert(error.code == <span class="hljs-string">'FOO_INVALID_ARGMUMENT'</span>)
    <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'Caught error of type %s with code %s. Stack trace follows.\n'</span>, error.name, error.code)

    <span class="hljs-built_in">console</span>.log(error.stack)
}</pre></div></div>

        </li>


        <li id="section-32">
            <div class="annotation">

              <div class="pilwrap ">
                <a class="pilcrow" href="#section-32">&#182;</a>
              </div>
              <p><strong>TODO</strong> Maybe start with nested e</p>

            </div>

            <div class="content"><div class='highlight'><pre>
<span class="hljs-keyword">return</span>
(<span class="hljs-keyword">async</span> <span class="hljs-function"><span class="hljs-keyword">function</span> (<span class="hljs-params"></span>) </span>{
    <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'CALLLED'</span>)
    <span class="hljs-keyword">async</span> <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">open</span> (<span class="hljs-params">file, flag, encoding</span>) </span>{
        <span class="hljs-keyword">try</span> {
            <span class="hljs-keyword">return</span> <span class="hljs-keyword">await</span> fs.readFile(file, { flag, encoding })
        } <span class="hljs-keyword">catch</span> (error) {
            <span class="hljs-keyword">throw</span> <span class="hljs-keyword">new</span> FooError(<span class="hljs-string">'FOO_FILE_IO'</span>, error)
        }
    }
    <span class="hljs-keyword">try</span> {
        <span class="hljs-keyword">await</span> open(<span class="hljs-string">'foo.txt'</span>, <span class="hljs-string">'r'</span>, <span class="hljs-string">'utf8'</span>)
    } <span class="hljs-keyword">catch</span> (error) {
        assert(error.code == <span class="hljs-string">'FOO_FILE_IO'</span>)
        <span class="hljs-built_in">console</span>.log(<span class="hljs-string">'Caught error of type %s with code %s. Stack trace follows.\n'</span>, error.name, error.code)
        <span class="hljs-built_in">console</span>.log(error.stack)
    }
}) ()</pre></div></div>

        </li>

    </ul>
  </div>
</body>
</html>
